[Desktop Entry]
Name=Mesmerized
Type=X-GNOME-Metatheme
Comment=A theme based on Obsidiana for KDE4

[X-GNOME-Metatheme]
GtkTheme=Mesmerize
MetacityTheme=Clearlooks
IconTheme=gnome-brave
GtkColorScheme=fg_color:#ffffffffffff,bg_color:#393939393939,text_color:#ffffffffffff,base_color:#20201f1f1f1f,selected_fg_color:#ffffffffffff,selected_bg_color:#8787afsfdfdf,tooltip_fg_color:#ffffffffffff,tooltip_bg_color:#212121212121
CursorTheme=Bluecurve
CursorSize=24
